title: hady.geek.nz
description: My personal voice and record of thoughts
url: http://hady.geek.nz

# Owner/author information
owner:
  name: Hady Osman
  avatar: bio-photo.jpg
  bio: 'Describe your self'
  email: hadyos@gmail.com

  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter: hadynz
  facebook: hady.osman
  linkedin: hadyosman

# Disqus Comments
disqus_short_name: hadysblog
disqus_show_comment_count: true

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:

# Github repositories
github_user: hadynz
github_repo_url: https://github.com/hadynz/hadynz.github.io/

# Jekyll Settings
timezone: Pacific/Auckland
future:      true
markdown: redcarpet
redcarpet:
  extensions: ['tables']
permalink: '/blog/:title/'
paginate: 20
paginate_path: '/blog/page/:num/'

exclude: ['Rakefile.rb', 'Gruntfile.js', 'package.json', 'node_modules', 'README.md', 'CNAME', 'bower_components']
safe: true

# Site Defaults
defaults:

  # ALL Website (Pages, Posts and Drafts)
  -
    scope:
      path: '' # empty string for all files
    values:
      comments: false
      meta: false
      large_header: false

  # ALL Posts
  -
    scope:
      path: ''
      type: "post"
    values:
      comments: true
      meta: true