#
# Blog Settings
#
author: Hady Osman
description: My personal voice and record of thoughts
url: http://hady.geek.nz
title: Hady's Blog
subtitle: My timeless repository of thought
gravatar_url: https://s.gravatar.com/avatar/dfed7b315b8b380d3e72dcbda22edd4b

# Github repositories
github_user: hadynz
github_repo_url: https://github.com/hadynz/hadynz.github.io/

# Twitter
twitter_user: hadynz
twitter_tweet_button: true

# Disqus Comments
disqus_short_name: hadynz
disqus_show_comment_count: true

# Google Analytics
#google_analytics_tracking_id: UA-177588-1

#
# Jekyll Settings
#
timezone: Pacific/Auckland
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
permalink: /archive/:year/:month/:day/:title/
paginate: 20
paginate_path: "page/:num"
category_dir: categories

host: 0.0.0.0
port: 4000
baseurl: ""
url: http://localhost:4000

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

exclude: ['Gemfile*', 'README.md', 'CNAME']