title: hady.geek.nz
description: My personal voice and record of thoughts
url: http://hady.geek.nz

# Owner/author information
owner:
  name: Hady Osman
  avatar: /assets/images/bio_photo.jpg
  email: hadyos@gmail.com

# Widget information
widget:
  # Discuss
  disqus:
    short_name: hadysblog
    show_comment_count: true

  # Google Analytics
  google_analytics:
    tracking_id: UA-1572641-7
    view_name: hady.geek.nz

# Jekyll Settings
timezone: Pacific/Auckland
future:      true
permalink: '/:categories/:title/'
exclude: ['Rakefile.rb', 'Gruntfile.js', 'package.json', 'node_modules', 'README.md', 'CNAME', 'bower_components', 'bower.json']
safe: true
markdown: kramdown
kramdown:
  use_coderay: true
  coderay:
    coderay_line_numbers: nil
    coderay_css: class

# Site Defaults
defaults:

  # ALL Website (Pages, Posts and Drafts)
  -
    scope:
      path: '' # empty string for all files
    values:
      comments: false
      meta: false
      large_header: false

  # ALL Posts
  -
    scope:
      path: ''
      type: 'post'
    values:
      categories: ['blog']
      comments: true
      meta: true
